# @package _global_

Dataset: 1d_rev_cond

x_dim: 1
y_dim: 1

# conditioning
data:
  dataset: type4
  x_std: 1
  y_std: 1
load: False

y_cond: null
x_cond_true: null

# transfer
transfer: False
Dataset_transfer: 2d
data_transfer: circle
cond_final: False


adaptive_mean: False
final_adaptive: True
final_var_scale: 1.
mean_final: torch.tensor([0.])
var_final: 1.*torch.tensor([1.])


# device
device: cpu
num_workers: 0
pin_memory: False

# training
use_prev_net: False
mean_match: False
ema: False
ema_rate: 0.999
grad_clipping: False
grad_clip: 1.0
npar: 10000
batch_size: 2000
num_iter: 200
cache_npar: 20000
n_ipf: 1
lr: 0.0001

# schedule
num_steps: 20
gamma_max: 0.01
gamma_min: 0.01
gamma_space: linspace
weight_distrib: False
weight_distrib_alpha: 100
fast_sampling: True
var_final_gamma_scale: True
double_gamma_scale: False


# logging
plot_npar: 500
test_npar: 500
log_stride: 50
gif_stride: ${num_iter}

