# @package _global_

# data
Dataset: stackedmnist
data:
  dataset: "inpaint_center"
  image_size: 28
  channels: 1
y_cond: test_ds[:8][1]
x_cond_true: test_ds[:8][0]

# transfer
transfer: False
Dataset_transfer: mnist
cond_final: False
cond_final_model:
  MODEL: BasicCond
  mean_scale: 1.
  std_scale: 1.
  adaptive_std: True


adaptive_mean: False
final_adaptive: False
mean_final: torch.zeros([${data.channels}, ${data.image_size}, ${data.image_size}])
var_final: 1*torch.ones([${data.channels}, ${data.image_size}, ${data.image_size}])
load: True

# device
device: cuda
num_workers: 0
pin_memory: True

# logging
log_stride: 10
gif_stride: 5000
plot_npar: 1000
test_npar: 100

# training
cache_refresh_stride: 2000
cache_npar: 2000
num_cache_batches: 1
use_prev_net: False
ema: True
ema_rate: 0.999
grad_clipping: True
grad_clip: 1.0
batch_size: 128
num_iter: 5000
n_ipf: 20
lr: 0.0001

# schedule
num_steps: 30
gamma_max: 0.1
gamma_min: 0.00001
gamma_space: linspace
weight_distrib: True
weight_distrib_alpha: 100
fast_sampling: True


