# @package _global_

defaults:
  - launcher: slurm_cpu
  - job
  - dataset: 1d_cond #celeba, 2d, stackedmnist
  - model: BasicCond #Basic, UNET
  - override hydra/launcher: submitit_slurm

name: "1d_cond"

# data
data_dir: ./data/  # TODO: buggy

# logging
LOGGER: CSV # NEPTUNE, CSV, NONE
CSV_log_dir: ./

cache_gpu: False
num_cache_batches: 1
cache_refresh_stride: 1000
plot_level: 1
mean_match: True
paths: 
  experiments_dir_name: experiments

# checkpoint
checkpoint_run: False
checkpoint_it: 13
checkpoint_pass: b  # b or f (skip b ipf run)
sample_checkpoint_f: ""
sample_checkpoint_b: ""
checkpoint_f: ""
checkpoint_b: ""
